#%RAML 1.0
title: TeamPathySpecs
version: v1
baseUri: http://teampathy
types:
  Member:
    properties:
      name: string
      kind: string
      price: number
    example:
      name: "Waterball"
      kind: "Person"
      price: 500

/members:
  get:
    responses:
      200:
        body:
          application/json:
            type: Member[]
  post:
    body:
      application/json:
        type: Member

  /{id}:
    put:
      body:
        application/json:
          type: Member
    delete:
       responses:
        204:
